# Generated by Django 5.2.1 on 2025-05-19 16:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('slug', models.SlugField(blank=True, help_text='Унікальний URL-ідентифікатор категорії', unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Опис категорії')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва товару')),
                ('slug', models.SlugField(blank=True, help_text='Унікальний URL-ідентифікатор товару', unique=True)),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('description', models.TextField(verbose_name='Опис товару')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ціна')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна зі знижкою')),
                ('status', models.CharField(choices=[('available', 'В наявності'), ('out_of_stock', 'Немає в наявності'), ('coming_soon', 'Очікується')], default='available', max_length=20, verbose_name='Статус')),
                ('condition', models.CharField(choices=[('new', 'Новий'), ('used', 'Вживаний'), ('refurbished', 'Відновлений')], default='new', max_length=20, verbose_name='Стан товару')),
                ('year', models.PositiveIntegerField(help_text='Рік випуску моделі BMW', validators=[django.core.validators.MinValueValidator(1916), django.core.validators.MaxValueValidator(2025)], verbose_name='Рік випуску')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендований товар')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість в наявності')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Зображення товару')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата додавання')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='bmwshop.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар BMW',
                'verbose_name_plural': 'Товари BMW',
                'ordering': ['-created_at'],
            },
        ),
    ]
